name: Docker Multi-Architecture Build

on:
    push:
        paths-ignore:
            - "**.md"
        branches:
            - master

jobs:
    build-docker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
              with:
                  platforms: all
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v3
              with:
                  version: latest
            - name: Login to Quay.io
              uses: docker/login-action@v3
              with:
                  registry: quay.io
                  username: ${{ secrets.QUAY_USERNAME }}
                  password: ${{ secrets.QUAY_PASSWORD }}
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  platforms: linux/amd64,linux/arm64/v8
                  push: true
                  tags: quay.io/invidious/youtube-trusted-session-generator:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
            - name: Build and push with HTTP API
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile.webserver
                  platforms: linux/amd64,linux/arm64/v8
                  push: true
                  tags: quay.io/invidious/youtube-trusted-session-generator:webserver
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
